
module.exports = {
  FIREBASE_URI: "https://jameson-moments.firebaseio.com",
  INSTAGRAM_CLIENT_ID: process.env.INSTAGRAM_CLIENT_ID,
  INSTAGRAM_CLIENT_SECRET: process.env.INSTAGRAM_CLIENT_SECRET,
  MOMENTS_WEBHOOK_URL: process.env.MOMENTS_WEBHOOK_URL,
  INSTAGRAM_SUBSCRIPTION_URL: process.env.INSTAGRAM_SUBSCRIPTION_URL,
  SESSION_SECRET: process.env.SESSION_SECRET,
  MANAGE_PHOTOS_URL: process.env.MANAGE_PHOTOS_URL,
  FIREBASE_SECRET: process.env.FIREBASE_SECRET
};